version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-mmedavv3a7b --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml
